name: at_gps_demo
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  args: ^2.3.1
  at_client: ^3.0.52
  at_onboarding_cli: ^1.1.1
  at_utils: ^3.0.10
  chalkdart: ^2.0.9
  logging: ^1.0.2
  mqtt_client: ^9.7.1

# dependency_overrides:
#   at_client:
#     git:
#       url: https://github.com/atsign-foundation/at_client_sdk.git
#       ref: enhance_notify_text_colin
#       path: at_client

