name: at_gps_demo
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {at_client: ^3.0.35, at_onboarding_cli: ^1.1.1, at_utils: ^3.0.10, mqtt_client: ^9.7.1}
